#!/bin/bash
# Verify install path
## kola:
##   timeoutMin: 30
##   tags: "needs-internet"
##   platforms: qemu  # additionalDisks is only supported on qemu
##   additionalDisks: ["20G"]
#
# Copyright (C) 2022 Red Hat, Inc.

set -xeuo pipefail

# See https://github.com/cgwalters/bootc-base-images
IMAGE=ghcr.io/cgwalters/fedora-oscore:latest
# TODO: better detect this, e.g. look for an empty device
DEV=/dev/vda

# Always work out of a temporary directory
cd $(mktemp -d)

case "${AUTOPKGTEST_REBOOT_MARK:-}" in
  "")
    podman run --rm -ti --privileged --pid=host --net=none -v /usr/bin/bootc:/usr/bin/bootc -v /usr/lib/bootc:/usr/lib/bootc ${IMAGE} bootc install --karg=foo=bar ${DEV}
    # In theory we could e.g. wipe the bootloader setup on the primary disk, then reboot;
    # but for now let's just sanity test that the install command executes.
    lsblk ${DEV}
    echo "ok install"

    # Now test install-to-filesystem
    # Wipe the device
    ls ${DEV}* | tac | xargs wipefs -af
    # This prepares the device and also runs podman directliy
    bootc internal-tests test-install-filesystem ${IMAGE} ${DEV}
    ;;
  *) echo "unexpected mark: ${AUTOPKGTEST_REBOOT_MARK}"; exit 1;;
esac
