# This really just depends on `cosa run`, which we could
# in theory split out separately at some point later.
FROM quay.io/coreos-assembler/coreos-assembler:latest
WORKDIR /srv
USER root
# Grab all of our ci scripts
COPY /ci/ /ci/
# And install our tests
COPY /tests/kolainst/ /usr/lib/coreos-assembler/tests/kola/bootc/
RUN ln -sr /ci/run-kola.sh /usr/bin/bootc-run-kola
USER builder
ENTRYPOINT []
CMD ["/usr/bin/bootc-run-kola"]
