# This Dockerfile generates a container image that installs bootc into
# a Fedora CoreOS image.
FROM quay.io/coreos-assembler/fcos-buildroot:testing-devel as builder
WORKDIR /src
COPY . .
RUN make test-bin-archive

FROM quay.io/fedora/fedora-coreos:testing-devel
COPY --from=builder /src/target/bootc.tar.zst /tmp
COPY ci/usr usr
RUN tar -xvf /tmp/bootc.tar.zst && ostree container commit 
